global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself

#  - job_name: 'go-service-1'
#    static_configs:
#      - targets: ['go-service-1:8080']  # Assuming Go service 1 is running in a container named 'go-service-1'
#
#  - job_name: 'go-service-2'
#    static_configs:
#      - targets: ['go-service-2:8080']  # Assuming Go service 2 is running in a container named 'go-service-2'
